version: "3.1"
services:
  db:
    image: postgres:14
    container_name: e-commerce-db
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  user-app:
    build:
      context: .
      dockerfile: Dockerfile.user
    container_name: user-app
    ports:
      - 8001:8001
